# Generated by Django 5.1 on 2024-12-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomStyleDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('style_dict', models.CharField(default={'back_corridor': {'height': '5.5vh', 'width': '10vw'}, 'corridor': {'height': '5vw'}, 'entrance': {'alignContent': 'center', 'backgroundColor': 'greenyellow', 'height': '5.5vh', 'justifyContent': 'center', 'width': '5vw'}, 'gap_upper': {'height': '14.3vh'}, 'gap_upper_left': {'height': '14.3vh', 'width': '5vw'}, 'screen': {'backgroundColor': 'rgb(58, 170, 170)', 'fontSize': 'x-large', 'width': '30vw'}, 'seats_and_entrance': {'display': 'flex', 'justifyContent': 'center', 'width': '45vw'}, 'seats_container': {'alignContent': 'center', 'display': 'grid', 'gap': '7px', 'gridTemplateColumns': 'repeat(8,1fr)', 'gridTemplateRows': 'repeat(4,1fr)', 'height': '35vh', 'justifyContent': 'center'}}, max_length=2048)),
            ],
        ),
        migrations.AddField(
            model_name='venue',
            name='room_style',
            field=models.ManyToManyField(related_name='venues', to='reserv.roomstyledict'),
        ),
    ]
