# Generated by Django 5.1 on 2024-09-12 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='room')),
                ('chair_a', models.IntegerField(default=0)),
                ('chair_b', models.IntegerField(default=0)),
                ('seat_count', models.IntegerField(default=0)),
                ('start', models.DateTimeField(verbose_name='Start')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
