# Generated by Django 5.1 on 2024-09-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='showtime',
            field=models.DateTimeField(verbose_name='showtime'),
        ),
    ]
