# Generated by Django 5.1 on 2024-09-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv', '0002_alter_venue_showtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='reservations',
            field=models.ManyToManyField(blank=True, null=True, related_name='venues', to='reserv.reservation'),
        ),
    ]
