# Generated by Django 5.1 on 2024-09-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv', '0002_reservation_venueid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='seat_a',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='seat_b',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='seat_c',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='seat_d',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='seat_a',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='seat_b',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='seat_c',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='seat_d',
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_001',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_001'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_002',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_002'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_003',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_003'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_004',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_004'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_005',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_005'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_006',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_006'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_007',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_007'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_008',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_008'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_009',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_009'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_010',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_010'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_011',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_011'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_012',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_012'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_013',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_013'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_014',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_014'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_015',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_015'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_016',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_016'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_017',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_017'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_018',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_018'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_019',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_019'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_020',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_020'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_021',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_021'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_022',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_022'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_023',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_023'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_024',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_024'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_025',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_025'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_026',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_026'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_027',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_027'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_028',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_028'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_029',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_029'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_030',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_030'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_031',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_031'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_032',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_032'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_033',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_033'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_034',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_034'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_035',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_035'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_036',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_036'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_037',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_037'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_038',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_038'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_039',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_039'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_040',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_040'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_041',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_041'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_042',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_042'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_043',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_043'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_044',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_044'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_045',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_045'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_046',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_046'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_047',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_047'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_048',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_048'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_049',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_049'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_050',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_050'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_051',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_051'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_052',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_052'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_053',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_053'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_054',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_054'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_055',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_055'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_056',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_056'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_057',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_057'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_058',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_058'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_059',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_059'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_060',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_060'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_061',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_061'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_062',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_062'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_063',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_063'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_064',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_064'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_065',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_065'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_066',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_066'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_067',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_067'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_068',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_068'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_069',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_069'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_070',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_070'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_071',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_071'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_072',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_072'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_073',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_073'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_074',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_074'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_075',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_075'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_076',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_076'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_077',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_077'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_078',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_078'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_079',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_079'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_080',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_080'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_081',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_081'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_082',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_082'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_083',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_083'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_084',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_084'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_085',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_085'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_086',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_086'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_087',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_087'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_088',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_088'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_089',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_089'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_090',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_090'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_091',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_091'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_092',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_092'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_093',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_093'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_094',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_094'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_095',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_095'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_096',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_096'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_097',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_097'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_098',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_098'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_099',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_099'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_100',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_100'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_101',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_101'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_102',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_102'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_103',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_103'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_104',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_104'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_105',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_105'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_106',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_106'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_107',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_107'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_108',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_108'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_109',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_109'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_110',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_110'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_111',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_111'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_112',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_112'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_113',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_113'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_114',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_114'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_115',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_115'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_116',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_116'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_117',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_117'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_118',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_118'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_119',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_119'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_120',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_120'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_121',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_121'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_122',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_122'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_123',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_123'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_124',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_124'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_125',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_125'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_126',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_126'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_127',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_127'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_128',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_128'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_129',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_129'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_130',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_130'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_131',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_131'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_132',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_132'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_133',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_133'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_134',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_134'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_135',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_135'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_136',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_136'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_137',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_137'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_138',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_138'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_139',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_139'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_140',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_140'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_141',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_141'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_142',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_142'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_143',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_143'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_144',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_144'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_145',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_145'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_146',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_146'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_147',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_147'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_148',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_148'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_149',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_149'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_150',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_150'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_151',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_151'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_152',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_152'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_153',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_153'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_154',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_154'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_155',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_155'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_156',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_156'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_157',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_157'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_158',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_158'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_159',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_159'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_160',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_160'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_161',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_161'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_162',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_162'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_163',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_163'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_164',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_164'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_165',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_165'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_166',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_166'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_167',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_167'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_168',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_168'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_169',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_169'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_170',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_170'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_171',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_171'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_172',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_172'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_173',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_173'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_174',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_174'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_175',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_175'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_176',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_176'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_177',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_177'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_178',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_178'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_179',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_179'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_180',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_180'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_001',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_001'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_002',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_002'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_003',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_003'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_004',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_004'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_005',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_005'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_006',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_006'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_007',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_007'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_008',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_008'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_009',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_009'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_010',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_010'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_011',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_011'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_012',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_012'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_013',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_013'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_014',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_014'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_015',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_015'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_016',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_016'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_017',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_017'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_018',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_018'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_019',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_019'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_020',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_020'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_021',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_021'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_022',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_022'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_023',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_023'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_024',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_024'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_025',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_025'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_026',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_026'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_027',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_027'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_028',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_028'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_029',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_029'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_030',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_030'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_031',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_031'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_032',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_032'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_033',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_033'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_034',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_034'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_035',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_035'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_036',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_036'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_037',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_037'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_038',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_038'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_039',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_039'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_040',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_040'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_041',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_041'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_042',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_042'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_043',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_043'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_044',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_044'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_045',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_045'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_046',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_046'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_047',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_047'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_048',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_048'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_049',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_049'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_050',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_050'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_051',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_051'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_052',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_052'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_053',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_053'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_054',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_054'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_055',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_055'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_056',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_056'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_057',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_057'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_058',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_058'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_059',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_059'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_060',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_060'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_061',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_061'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_062',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_062'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_063',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_063'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_064',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_064'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_065',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_065'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_066',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_066'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_067',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_067'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_068',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_068'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_069',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_069'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_070',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_070'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_071',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_071'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_072',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_072'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_073',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_073'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_074',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_074'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_075',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_075'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_076',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_076'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_077',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_077'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_078',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_078'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_079',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_079'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_080',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_080'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_081',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_081'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_082',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_082'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_083',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_083'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_084',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_084'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_085',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_085'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_086',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_086'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_087',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_087'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_088',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_088'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_089',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_089'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_090',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_090'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_091',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_091'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_092',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_092'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_093',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_093'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_094',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_094'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_095',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_095'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_096',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_096'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_097',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_097'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_098',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_098'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_099',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_099'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_100',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_100'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_101',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_101'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_102',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_102'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_103',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_103'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_104',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_104'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_105',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_105'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_106',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_106'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_107',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_107'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_108',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_108'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_109',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_109'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_110',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_110'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_111',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_111'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_112',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_112'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_113',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_113'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_114',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_114'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_115',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_115'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_116',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_116'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_117',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_117'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_118',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_118'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_119',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_119'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_120',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_120'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_121',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_121'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_122',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_122'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_123',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_123'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_124',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_124'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_125',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_125'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_126',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_126'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_127',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_127'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_128',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_128'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_129',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_129'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_130',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_130'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_131',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_131'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_132',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_132'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_133',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_133'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_134',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_134'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_135',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_135'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_136',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_136'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_137',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_137'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_138',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_138'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_139',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_139'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_140',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_140'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_141',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_141'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_142',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_142'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_143',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_143'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_144',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_144'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_145',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_145'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_146',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_146'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_147',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_147'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_148',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_148'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_149',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_149'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_150',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_150'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_151',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_151'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_152',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_152'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_153',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_153'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_154',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_154'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_155',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_155'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_156',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_156'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_157',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_157'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_158',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_158'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_159',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_159'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_160',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_160'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_161',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_161'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_162',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_162'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_163',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_163'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_164',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_164'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_165',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_165'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_166',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_166'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_167',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_167'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_168',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_168'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_169',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_169'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_170',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_170'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_171',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_171'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_172',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_172'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_173',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_173'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_174',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_174'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_175',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_175'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_176',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_176'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_177',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_177'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_178',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_178'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_179',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_179'),
        ),
        migrations.AddField(
            model_name='venue',
            name='seat_180',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='seat_180'),
        ),
    ]
