# Generated by Django 5.1 on 2024-09-12 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserv', '0002_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='chair_a',
            new_name='seat_a',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='chair_b',
            new_name='seat_b',
        ),
    ]
