# Generated by Django 5.1 on 2024-12-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv', '0002_roomstyledict_venue_room_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomstyledict',
            name='style_dict',
            field=models.JSONField(default=dict),
        ),
    ]
