# Generated by Django 5.1 on 2024-10-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv', '0004_remove_reservation_seat_001_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='seatnames',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
