# Generated by Django 5.1 on 2024-12-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv', '0004_roomstyledict_capacity_roomstyledict_inner_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='capacity',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Keresztnév'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Vezetéknév'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_name',
            field=models.CharField(max_length=100, verbose_name='Tere neve'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='seat_count',
            field=models.IntegerField(default=0, verbose_name='Foglalt székek száma'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='seatnames',
            field=models.CharField(default=' ', max_length=1000, verbose_name='Foglalt helyek'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='showtime',
            field=models.DateTimeField(verbose_name='Vetítési időpont'),
        ),
        migrations.AlterField(
            model_name='roomstyledict',
            name='capacity',
            field=models.IntegerField(default=0, verbose_name='Férőhelyek száma'),
        ),
        migrations.AlterField(
            model_name='roomstyledict',
            name='room_name',
            field=models.CharField(max_length=100, verbose_name='Terem neve'),
        ),
    ]
