# Generated by Django 5.1 on 2024-10-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv', '0006_remove_reservation_seatnames'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='seatnames',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
