# Generated by Django 5.1 on 2024-11-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserv', '0007_reservation_seatnames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='show',
            name='rating',
            field=models.CharField(choices=[('Korhatárra való tekintet nélkül megtekinthető', 'Korhatárra való tekintet nélkül megtekinthető'), ('6 éven felülieknek', '6 éven felülieknek'), ('12 éven felülieknek', '12 éven felülieknek'), ('16 éven felülieknek', '16 éven felülieknek'), ('18 éven felülieknek', '18 éven felülieknek')], max_length=50, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='room_name',
            field=models.CharField(choices=[('Kisterem', 'Kisterem'), ('Nagyterem', 'Nagyterem'), ('Közepes terem', 'Közepes terem')], max_length=100, verbose_name='Room name'),
        ),
    ]
